### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by RandomAltThing** [DragonetMC/DragonetPEAddon#13]
**I am going to rewrite the UI areas of this app completely. Here Is a list of what will be done:**

- [x] Add an 'about' page to the app.
- [x] Add a settings page.
- [ ] Add a versions page.
- [ ] Add some of the main dragonet code so we can run a server on the device
- [ ] Make the modscripts auto-install.
- [ ] Possibly a widget displaying server info!
- [ ] Implement a working support library :P

**Comment by DefinitlyEvil** [comment]
I plan to make a MCPE server on local device, and maintain a TCP connection to the Dragonet server. This app sends all MCPE encoded packets through TCP connection and that TCP connection can also transit some addon script data. I hope you understand me. ;)

**Comment by RandomAltThing** [comment]
Kind of. I'm not good with all that net stuff

**Comment by DefinitlyEvil** [comment]
@RandomAltThing You can just do the GUI and config loading/saving part.

**Comment by RandomAltThing** [comment]
Alright. Right now I'm learning addons and I managed to add a block (#hype)

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Can you create a new branch on this repo called *rewrite*?

**Comment by RandomAltThing** [comment]
Why can't we just make it possible to host the server on the device like pocket mine?

**Comment by DefinitlyEvil** [comment]
@RandomAltThing Fool, this app let's people connects to Dragonet server together. It's useless host a local server with only one person. The adding ebales some MC PC features. Just do your parts and stop asking.

**Comment by RandomAltThing** [comment]
You should create a repo called "DroidDragonet" to actually host the server on the device. It was even added to the poll on mine craft forums.

**Comment by DefinitlyEvil** [comment]
@RandomAltThing Alright, we will do it later.
