### ISSUE TITLE
Modscript rewrite & deletion

### ISSUE THREAD

**Issue by RandomAltThing** [DragonetMC/DragonetPEAddon#16]
It has just occurer to me that the mod script items use many of the same textures but we will need to use a texture pack to change them. For example all spawn eggs are same texture so when we apply the texture pack it will change all the spawn eggs to that texture. I'm probably not making any Sense but we do need to rewrite them.

**Comment by Creeperface01** [comment]
Because in blocklauncher 1.8 is limited amount of textures. In BL 1.9 too but zhuowei added option for crated more textures but i dont know how for now

**Comment by Creeperface01** [comment]
So i add different textures only for important things.

**Comment by RandomAltThing** [comment]
I will check his twitter he is bound to post it there

**Comment by Creeperface01** [comment]
No unlimited amount of textures! 
https://github.com/zhuowei/MCPELauncher/wiki/Texture-packs

**Comment by DefinitlyEvil** [comment]
@Creeperface01 @RandomAltThing Why did you remove the script for communicating with the android app? The script and the app communicates with android broadcasts.

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Look in /assets/modscript

**Comment by RandomAltThing** [comment]
Wait WHAT? It is delete? Errm I can get a backup from my phone I downloaded the mod script before so its all good.

**Comment by RandomAltThing** [comment]
Fixed

**Comment by Creeperface01** [comment]
I think it didn't work in BL

**Comment by DefinitlyEvil** [comment]
@RandomAltThing Could you plz test out the script and see if it can call to Android stuffs please?

**Comment by RandomAltThing** [comment]
No I can't because I'm using a slightly older block launcher without Item.defineArmor

**Comment by RandomAltThing** [comment]
And android.widget.Toast gives error just use print()

**Comment by DefinitlyEvil** [comment]
So it seems that the script can not call to Android Java.
