### ISSUE TITLE
Needs rewrite

### ISSUE THREAD

**Issue by RandomAltThing** [DragonetMC/DragonetPEAddon#8]
@TheMCPEGamer @DragonetMC This needs a rewrite. I am happy to spend countless hours improving. Here are some things that I can improve on:

**•**Make the Dragonet app auto-install the scripts
**•**Make the Dragonet app more user-friendly
**•**Update the scripts

The mod scripts would be strored in the apps' */assets/modscript* folder so I can make it auto install.

#My TODO list for Dragonet

[  ] Get @byteandahalf to teach me addons so I can add the blocks natively
[x] Commit to this repo
[  ] Make this app user friendly
[  ] Auto install modscripts

**Comment by DefinitlyEvil** [comment]
This app also a networking proxy for MCPE.

**Comment by RandomAltThing** [comment]
Alright. I have started an addon version (very basic as I'm learning) but its coming along good!

**Comment by DefinitlyEvil** [comment]
Okay.
